# Generated by Django 4.2.7 on 2025-03-06 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('match_type', models.CharField(choices=[('SOCIAL', '소셜 매치'), ('TEAM', '팀 매치'), ('TOURNAMENT', '토너먼트')], max_length=10, verbose_name='매치 유형')),
                ('date', models.DateField(verbose_name='경기 날짜')),
                ('start_time', models.TimeField(verbose_name='시작 시간')),
                ('end_time', models.TimeField(verbose_name='종료 시간')),
                ('status', models.CharField(choices=[('OPEN', '모집중'), ('CLOSED', '모집완료'), ('CANCELED', '취소됨'), ('COMPLETED', '경기완료')], default='OPEN', max_length=10, verbose_name='상태')),
                ('max_players', models.IntegerField(verbose_name='최대 인원')),
                ('skill_level', models.CharField(choices=[('BEG', '입문'), ('INT', '중급'), ('ADV', '고급'), ('ALL', '모든 수준')], default='ALL', max_length=3, verbose_name='실력 수준')),
                ('gender', models.CharField(choices=[('MALE', '남성'), ('FEMALE', '여성'), ('MIXED', '혼성')], default='MIXED', max_length=6, verbose_name='성별')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='참가비')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('team_match', models.BooleanField(default=False, verbose_name='팀 매치 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('home_score', models.IntegerField(blank=True, null=True, verbose_name='홈팀 점수')),
                ('away_score', models.IntegerField(blank=True, null=True, verbose_name='원정팀 점수')),
            ],
            options={
                'verbose_name': '매치',
                'verbose_name_plural': '매치들',
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='MatchParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REGISTERED', '등록됨'), ('CANCELED', '취소됨'), ('ATTENDED', '참석함'), ('NOSHOW', '불참')], default='REGISTERED', max_length=10, verbose_name='상태')),
                ('payment_status', models.BooleanField(default=False, verbose_name='결제 상태')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
            options={
                'verbose_name': '매치 참가자',
                'verbose_name_plural': '매치 참가자들',
            },
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score', models.IntegerField(verbose_name='홈팀 점수')),
                ('away_score', models.IntegerField(verbose_name='원정팀 점수')),
                ('summary', models.TextField(blank=True, verbose_name='경기 요약')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='matches.match')),
            ],
            options={
                'verbose_name': '매치 결과',
                'verbose_name_plural': '매치 결과들',
            },
        ),
    ]
