# Generated by Django 4.2.7 on 2025-03-06 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='구장명')),
                ('address', models.CharField(max_length=255, verbose_name='주소')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='위도')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='경도')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('surface_type', models.CharField(choices=[('GRASS', '천연잔디'), ('ARTIFICIAL', '인조잔디'), ('FUTSAL', '풋살장')], max_length=20, verbose_name='구장 표면')),
                ('size', models.CharField(choices=[('5', '5인용'), ('6', '6인용'), ('7', '7인용'), ('11', '11인용')], max_length=2, verbose_name='구장 크기')),
                ('image', models.ImageField(blank=True, null=True, upload_to='venue_images/', verbose_name='구장 이미지')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='시간당 가격')),
                ('opening_time', models.TimeField(verbose_name='개장 시간')),
                ('closing_time', models.TimeField(verbose_name='폐장 시간')),
                ('has_parking', models.BooleanField(default=False, verbose_name='주차 가능 여부')),
                ('has_shower', models.BooleanField(default=False, verbose_name='샤워 시설 여부')),
                ('has_locker', models.BooleanField(default=False, verbose_name='락커 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '구장',
                'verbose_name_plural': '구장들',
            },
        ),
        migrations.CreateModel(
            name='VenueImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='venue_images/', verbose_name='이미지')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='venues.venue')),
            ],
            options={
                'verbose_name': '구장 이미지',
                'verbose_name_plural': '구장 이미지들',
            },
        ),
        migrations.CreateModel(
            name='VenueReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='평점')),
                ('comment', models.TextField(verbose_name='리뷰 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='venues.venue')),
            ],
            options={
                'verbose_name': '구장 리뷰',
                'verbose_name_plural': '구장 리뷰들',
                'unique_together': {('venue', 'user')},
            },
        ),
    ]
