# Generated by Django 4.2.7 on 2025-03-06 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='팀명')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='team_logos/', verbose_name='로고')),
                ('description', models.TextField(blank=True, verbose_name='팀 소개')),
                ('level', models.CharField(choices=[('BEG', '입문'), ('INT', '중급'), ('ADV', '고급'), ('PRO', '프로')], default='BEG', max_length=3, verbose_name='팀 수준')),
                ('rating', models.FloatField(default=1000.0, verbose_name='팀 레이팅')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('matches_played', models.IntegerField(default=0, verbose_name='경기 수')),
                ('wins', models.IntegerField(default=0, verbose_name='승리 수')),
                ('draws', models.IntegerField(default=0, verbose_name='무승부 수')),
                ('losses', models.IntegerField(default=0, verbose_name='패배 수')),
                ('goals_scored', models.IntegerField(default=0, verbose_name='득점')),
                ('goals_conceded', models.IntegerField(default=0, verbose_name='실점')),
            ],
            options={
                'verbose_name': '팀',
                'verbose_name_plural': '팀들',
            },
        ),
        migrations.CreateModel(
            name='TeamJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, verbose_name='가입 메시지')),
                ('status', models.CharField(choices=[('PENDING', '대기중'), ('ACCEPTED', '수락됨'), ('REJECTED', '거절됨')], default='PENDING', max_length=10, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='요청일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='처리일')),
            ],
            options={
                'verbose_name': '팀 가입 요청',
                'verbose_name_plural': '팀 가입 요청들',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CAPTAIN', '주장'), ('MANAGER', '매니저'), ('PLAYER', '선수')], default='PLAYER', max_length=10, verbose_name='역할')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
            options={
                'verbose_name': '팀 멤버',
                'verbose_name_plural': '팀 멤버들',
            },
        ),
    ]
