# Generated by Django 4.2.7 on 2025-03-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_recruiting',
            field=models.BooleanField(default=True, verbose_name='모집 중'),
        ),
        migrations.AddField(
            model_name='team',
            name='region',
            field=models.CharField(choices=[('seoul', '서울'), ('gyeonggi', '경기'), ('incheon', '인천'), ('other', '기타')], default='seoul', max_length=20, verbose_name='활동 지역'),
        ),
    ]
