# Generated by Django 4.2.7 on 2025-03-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_teamjoinrequest_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='position',
            field=models.CharField(blank=True, choices=[('GK', '골키퍼'), ('DF', '수비수'), ('MF', '미드필더'), ('FW', '공격수')], max_length=2, null=True, verbose_name='포지션'),
        ),
    ]
