# Generated by Django 4.2.7 on 2025-03-08 15:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0005_teammember_position'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teamjoinrequest',
            unique_together={('team', 'user')},
        ),
    ]
